### ISSUE TITLE
feram 0.24.02 へのアップデート

### ISSUE THREAD

**Issue by t-nissie** [cmsi/MateriAppsLive#102]
feram-0.23.00unstable
=====================
西松です。
feram-0.23.00unstable.tar.xz を https://sourceforge.net/projects/loto/files/feram/unstable/ から
リリースしました。

MD5 (feram-0.23.00unstable.tar.xz) = c0440fddbeb51ae93c76d9a7711e9de0

変更などは下記の通りですが、MateriApps Live!用に

 * make installでインストールされるツール類がすべてferam_ではじまるようにした。
 * make checkが数分以内に終わるように、結合テストを行わないようにした。

の変更もしました。

８月までには安定版の0.24.00を出したいと思っています。
MateriApps Live!への取り入れについてご意見をいただければ幸いです。

よろしくお願い申し上げます。

## Changes
From this feram-0.23.00unstable, internal data structure is largely modified.
You may be able to speed up your calculations with the `padding_y` tag.
It is developed under a branch of subversion,
https://sourceforge.net/p/loto/code/HEAD/tree/feram/branches/newplan/ .
See README.en or README.ja and src/coord_module.F.

From this feram-0.23.00unstable, you can do `make check` on Windows.

From this feram-0.23.00unstable, some tools are renamed by
adding feram_ in their heads.

A bug in src/27example-BaTiO3-new-param-E_wave/generator.sh is fixed.
You can generate some input files automatically now.

## Known bug
OpenMP-parallelization does not work efficiently over two or
more NUMA chips of Intel Xeon CPUs which is released after
2011 (Sandy Bridge, Ivy Bridge, Haswell, Broadwell, ...).
Execute feram within single chip by using numactl(8) command.

Intel Fortran (ifort) cannot make a fast executable,
because there is no optimized fftw_plan_many_dft_r2c() nor
ftw_plan_many_dft_c2r() in Intel Math Kernel Library (MKL), so far.

Hysteresis loop calculations of **film** goes wrong.
A strange peak appears in the beginning.
See src/23example-BaTiO3-new-param-hl-film-acoustic-mass/.
Bulk calculations go very fine.

    Version | acoustic_mass_amu | Good or N.G.
    ------- | ----------------- | ------------
    0.20.00 | with              | strange peak
    0.20.00 | without           | Good
    0.21.04 | with              | strange peak
    0.21.04 | without           | Good
    0.22.00 | with              | strange peak
    0.22.00 | without           | Good
    0.22.01 | with              | strange peak
    0.22.01 | without           | Good
    0.22.02 | with              | strange peak
    0.22.02 | without           | Good
    0.22.03 | with              | paraelectric
    0.22.03 | without           | paraelectric
    0.22.04 | with              | paraelectric
    0.22.04 | without           | paraelectric
    0.22.05 | with              | strange peak
    0.22.05 | without           | OK
    0.22.06 | with              | strange peak
    0.22.06 | without           | OK
    0.23.00 | with              | strange peak
    0.23.00 | without           | OK

**Comment by wistaria** [comment]
ありがとうございます。次回MateriApps LIVE!更新時に feram も同時にアップデートします。

**Comment by wistaria** [comment]
無事 Debian Package の作成が行えることと、テストが通ることは確認したのですが、unstable 版を Debian Package としてリリースして良いのかどうか迷っています。やはり 8月の stable 版まで待った方が良いでしょうか？ > @t-nissie

**Comment by t-nissie** [comment]
deb packageができてよかったです。ツール類のファイル名はそのままferam_fooでいこうと思います。stable版のリリースと同時にwebのドキュメントやチュートリアルをいっせいに置き換える予定です。それまではMateriApps LIVE!には一つ古い0.22.06を入れておくのがよいかと思います。タイトルを「アップデート」ではなくて「ご意見うかがい」とかにするべきでした。お騒がせして申し訳ありません。いちどcloseします。

**Comment by wistaria** [comment]
了解です。0.24.0が出るまでは、0.22.06のままにしておきます。

**Comment by t-nissie** [comment]
西松です。feram-0.24.02.tar.xz を https://sourceforge.net/projects/loto/files/feram/feram-0.24.02/ から肉の日リリースしました。MateriApps LIVE!に入れていただければ幸いです。本イシューを再オープンします。よろしくお願いします。

**Comment by wistaria** [comment]
0.24.02 の Debian パッケージを作成しました https://github.com/cmsi/ma-feram/releases/tag/0.24.02-1
明日リリース予定の MateriApps LIVE! 1.8 に入れます
