### ISSUE TITLE
C-Toolsの追加

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#103]
C-Tools http://ma.cms-initiative.jp/ja/listapps/C-Tools

**Comment by wistaria** [comment]
吉澤さん> MateriApps Live!の中のフォルダの /usr/share/xtapp/check/ に http://white.phys.s.u-tokyo.ac.jp/~yoshiz-k/al.cg を加えて頂けるとxTAPPのチュートリアルをするときに助かります。

**Comment by wistaria** [comment]
al.cg はすでに xtapp パッケージに含まれていました @yoshizk07

**Comment by wistaria** [comment]
c-tools_0.3.1-1 を作成・公開 235c09bcedace6129ac077930bd8c3315c232098
動作テストをよろしくお願いします > @yoshizk07

**Comment by yoshizk07** [comment]
藤堂先生、TAPIOCAのアップデートとC-Toolsのインストールどうもありがとうございます。

al.cg は、xtappパッケージの方に入っていましたか。
確認せずにすみません。
どうもありがとうございました。

動作テストの件は了解致しました。
