### ISSUE TITLE
Octa

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#106]

**Comment by wistaria** [comment]
ライセンス・配布条件を調査

**Comment by wistaria** [comment]
吉澤さんが開発者にライセンス確認中

**Comment by wistaria** [comment]
開発者に最終確認中。並行してパッケージの作成を開始する

**Comment by wistaria** [comment]
Octaのインストール・実行はできた
全体サイズがかなり大きいためパッケージ化に工夫が必要

次期バージョンで公開予定

**Comment by wistaria** [comment]
octa-setup にするか？

**Comment by yoshizk07** [comment]
このアプリはうまく入力ファイルを作れないと使えないので
（うまくモデリングできないと使えないので）
それでも良いと思います。

**Comment by wistaria** [comment]
Done
https://github.com/cmsi/ma-octa/releases/tag/8.3-1
