### ISSUE TITLE
一本のUSBでUSB Boot & VirutalBox用仮想ディスクイメージの入ったFAT32を共存させられるか？

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#108]

**Comment by rigarash** [comment]
USBが/dev/sdaにあるとして、/dev/sda1をLive、/dev/sda2をpersistence用ext4、sda3をVFATにすると大丈夫ではないかと思います。しかし、i386とx86_64のOVAを両方乗せるとそれだけで5GB程度になるため、現在の配布用のUSBメモリは8GBしか容量がないため、余裕がないように思われます。

**Comment by wistaria** [comment]
実際に試してみましたか？
以前試した時は、Windows も Mac も /dev/sda1 を無視してくれず、「フォーマットしますか？」と訊いてきました、、、
