### ISSUE TITLE
feramのアップデート

### ISSUE THREAD

**Issue by t-nissie** [cmsi/MateriAppsLive#167]
feram-0.26.01をリリースしました。
https://sourceforge.net/projects/loto/files/feram/feram-0.26.01/
アップデートをお願いできれば幸いです。
make checkで３２のテストがあります。
マシンのパワーにもよりますが、数分で終わるはずです。
よろしくお願い申し上げます。

**Comment by wistaria** [comment]
バージョン2.0でアップデートします

**Comment by wistaria** [comment]
Updated to 0.26.04 in https://github.com/cmsi/ma-feram/releases/tag/0.26.04-1
