### ISSUE TITLE
RIST東京事務所での講習会

### ISSUE THREAD

**Issue by yoshizk07** [cmsi/MateriAppsLive#207]
MateriAppsLive＋材料系アプリ@RIST東京事務所
の講習会を企画した

**Comment by yoshizk07** [comment]
11/21　MateriApps LIVE! + LAMMPS講習会
受講者から Gromacs の version up の要望があった

**Comment by yoshizk07** [comment]
3月ごろ　MateriApps LIVE! + 第一原理計算（たぶんQE）
を開催予定

**Comment by wistaria** [comment]
gromacsの最新版は2016.4ですね。バージョンアップの件、了解しました

**Comment by yoshizk07** [comment]
よろしくお願い致します。
それから、たぶん gromacs の最新版は、コンパイラがC++11に対応していないとビルド出来ないと思います。
（gromacsは、2016版からC++になったので。）

また、MateriApps LIVE!自体をアップデートして頂かなくても、
aptitude でアップデート出来るようにパッケージ化をして頂ければ大丈夫です。

**Comment by yoshizk07** [comment]
11/21　MateriApps LIVE! + LAMMPS講習会
講習会テキスト
http://www.hpci-office.jp/invite2/documents2/20171121_RIST_LAMMPS.pdf

**Comment by yoshizk07** [comment]
可能なら、可視化アプリ OVITO
https://ovito.org/
を入れてほしいです。
（最近、VMDより良いという噂も聞きます）

**Comment by wistaria** [comment]
ありがとうございます > @yoshizk07 
それぞれ、以下に展開済み
* Issue #208 Gromacs最新版Debianパッケージの作成
* Issue #209 可視化アプリOVITOのDebianパッケージの作成
* LAMMPS講習テキスト: https://github.com/cmsi/MateriAppsLive/wiki/MaLiveTutorial にリンクを追加
