### ISSUE TITLE
The GPG key for the debian repository has expired

### ISSUE THREAD

**Issue by jochym** [cmsi/MateriAppsLive#241]
The repository key has expired few days ago. Please update the keyring - this makes the repo difficult to use.

**Comment by wistaria** [comment]
@jochym 
Thank you for your report! I will update the GPG key in a few days.

**Comment by wistaria** [comment]
@jochym 
The GPG key for the MateriApps LIVE! repository has been updated. Please update the key as follows:
```
wget http://exa.phys.s.u-tokyo.ac.jp/archive/MateriApps/keys/materiapps.gpg
sudo cp -f materiapps.gpg /etc/apt/trusted.gpg.d/materiapps.gpg
sudo rm -f /etc/apt/trusted.gpg 
sudo apt-get update
sudo apt-get install materiapps-keyring
```
