### ISSUE TITLE
MA LIVE! 紹介＆設定指南スライドの更新

### ISSUE THREAD

**Issue by yomichi** [cmsi/MateriAppsLive#246]
https://www.slideshare.net/cms_initiative/clipboards/how-to-setup-materiapps-live
にある MA LIVE! 紹介＆設定指南スライドですが、13ページ目にある LXTerminal の場所が古いままです（最新のMALIVE! では System Tools にある）。
他にも古い記述があるかもしれません。

**Comment by wistaria** [comment]
修正します
