### ISSUE TITLE
Can not install VESTA on Ubuntu.

### ISSUE THREAD

**Issue by CHN-beta** [cmsi/MateriAppsLive#252]
I have read the [wiki](https://github.com/cmsi/MateriAppsLive/wiki/UsingMateriAppsInDebian-en), and successfully installed akaikkr:

```bash
wget https://sourceforge.net/projects/materiappslive/files/Debian/sources/materiapps-bionic.list
sudo cp materiapps-bionic.list /etc/apt/sources.list.d
sudo apt-get -o Acquire::AllowInsecureRepositories=true update
sudo apt-get -y --allow-unauthenticated install materiapps-keyring
sudo apt-get update
sudo apt-get install akaikkr
```

But I can not find out how to install VESTA:

```bash
sudo apt install vesta
```

It tells me the package "vesta" can not be found.

Please help me.

**Comment by wistaria** [comment]
We are now preparing binary packages for Debian Buster / Ubuntu Xenial / Ubuntu Bionic very slowly...
Please see https://github.com/cmsi/MateriAppsLive/issues/227 for the progress.
I will give a higher priority VESTA package.
Please wait until the package will be ready.

**Comment by wistaria** [comment]
@CHN-beta 
I have prepared and uploaded a Debian package of VESTA for Ubuntu Bionic.
Please try
```
sudo apt-get update
sudo apt-get install vesta
```

**Comment by CHN-beta** [comment]
It works. Thank you.

ありがどうございます。:-D
