### ISSUE TITLE
Vesta launcher's icon

### ISSUE THREAD

**Issue by emmegamma** [cmsi/MateriAppsLive#288]
The launcher for Vesta is missing an icon, though all the elements are present.

Please add

`Icon=/usr/share/vesta/img/logo@2x.png`

to the .desktop file ( `/usr/share/applications/vesta.desktop` )

**Comment by wistaria** [comment]
@emmegamma 
Thanks for your report. Fixed in 3.5.5-2.
Please try
```
sudo apt-get update
sudo apt-get install vesta
```
