### ISSUE TITLE
Web講習会(オンラインチュートリアル)のための準備wikiページについて

### ISSUE THREAD

**Issue by skasamatsu** [cmsi/MateriAppsLive#297]
https://github.com/cmsi/MateriAppsLive/wiki/OnlineTutorial
「exeファイルやdmgファイル」と書いてあるところ、Windowsだとデフォルトで拡張子を表示しないので、躓きポイントかもしれません。

**Comment by wistaria** [comment]
@skasamatsu 
どう書けば伝わります？？

**Comment by skasamatsu** [comment]
@wistaria もう、動画しかないですかねぇ…

**Comment by wistaria** [comment]
とりあえず、「WindowsではVirutalBox-6.1...-Win.exeファイル、macOSではVirutalBox-6.1...-OSX.dmgを」と直しました

**Comment by yomichi** [comment]
@wistaria 
別件ですが、事前に setup.pdf を最初から最後まで試そうとした結果、15ページ目にある仮想CDドライブをつかってiso イメージを読み出す設定で「iso イメージをどうすればいいのかわからない（持ってない）」ことで躓いてしまった人がいらっしゃいました。
そもそもiso イメージを仮想マシンの中から読みたくなるケースって、ほとんど無いようなきがします。
（あるいは、そもそも何のための設定なのかを、あと一言書いたほうが良い？）

**Comment by wistaria** [comment]
@yomichi 
講習会のサンプルファイル一式をisoで配ればよいのでは、という話があって、setup.pdfにもその説明を加えた気がします
「講習会等で、、、の場合には」という文言を追加します

**Comment by wistaria** [comment]
isoイメージについての記述はsetup.pdfから削除しました
