### ISSUE TITLE
Debian bookworm support

### ISSUE THREAD

**Issue by mueslo** [cmsi/MateriAppsLive#315]
Thanks for maintaining this repository!

It would be great if upcoming Debian 12 would also get packages.

**Comment by wistaria** [comment]
I expect that Debian bookworm will be released next August or September. I will start working on the bookworm support in early 2023.

**Comment by alexmyczko** [comment]
It's been released long ago... I wasn't able to figure if vesta sources are available publicly or not. What about an official Debian package (if license allows)?

**Comment by wistaria** [comment]
I have published Vesta Debian package for boomworm. Following https://github.com/cmsi/MateriAppsLive/wiki/UsingMateriAppsInDebian-en , execute
```
sudo apt -y install wget
wget https://sf.net/projects/materiappslive/files/Debian/sources/setup.sh
sudo sh setup.sh
sudo apt -y install vesta
```

**Comment by alexmyczko** [comment]
@wistaria do you know if the sources are available and if so would you be interested maintaining an official debian package?

**Comment by wistaria** [comment]
@alexmyczko hey do not want to release the source code. The Debian VESTA packages of MateriApps LIVE! just includes the binary files released on the VESTA web page, with permission for binary redistribution.
