### ISSUE TITLE
QE w/ ESM-RISM

### ISSUE THREAD

**Issue by yomichi** [cmsi/MateriAppsLive#316]
@wistaria 
来週の木曜日に QE/ESM-RISM の講習会があるので、debian package の作成をお願いしたいです。

https://gitlab.com/minoru-otani/q-e
rism_expand_onesite ブランチです。
（最終的に必要となる実行バイナリは `pw.x` と`pprism.x` です）

ただ、現状はQE 6.7 でして、そのままやるとすでに用意されているQE 7.1 とバッティングしてしまいそうです。
デフォルトはパスを通さないようにして、必要なときには適当に `source` するとかでも良いだろうには思っています。

**Comment by wistaria** [comment]
@yomichi 了解です。準備してみます

**Comment by wistaria** [comment]
@yomichi 作成してみました
```
$ sudo apt-get update
$ sudo apt-get install quantum-espresso-esm-rism
$ source /usr/share/espresso-esm-rism/bin/setup.sh
```
で pw.x と pprism.x が使えるようになります
動作確認お願いします

**Comment by yomichi** [comment]
ありがとうございます、無事に動くことを確認しました（Docker 版）

**Comment by yomichi** [comment]
@wistaria 
すみません、 `pw.x` と `pprism.x` も入れていただけると幸いです（特に `rism1d.x` ）

**Comment by wistaria** [comment]
@yomichi 
> すみません、 `pw.x` と `pprism.x` も入れていただけると幸いです（特に `rism1d.x` ）

ん？`pw.x` と `pprism.x` は入っていると思いますが、、、
`rism1d.x` だけ追加すればよいですか？

**Comment by yomichi** [comment]
すみません、なんかよくわからないこと言っていました。
rism1d.x ですね。

**Comment by wistaria** [comment]
いれました
https://github.com/cmsi/MateriAppsPackages/releases/tag/espresso-esm-rism-6.7-2
