### ISSUE TITLE
GPG key の有効期限切れ？

### ISSUE THREAD

**Issue by masatoshihanai** [cmsi/MateriAppsLive#327]
https://github.com/cmsi/MateriAppsLive/tree/master/keys
より、
“Extended expiration date of gpg key to 2024-05-10” 
のcommit があり、GPG key の有効期限が切れているようです。

**Comment by wistaria** [comment]
@masatoshihanai ありがとうございます。うっかりしてました。
鍵の有効期限を延長しました。以下で更新可能できます。
`curl -fsSL https://sf.net/projects/materiappslive/files/Debian/sources/update.sh | sudo bash`

**Comment by wistaria** [comment]
https://github.com/cmsi/MateriAppsLive/wiki/FAQ#package に追記しました

**Comment by masatoshihanai** [comment]
ありがとうございました！

**Comment by wistaria** [comment]
スクリプトを以下に移動
* `https://sf.net/projects/materiappslive/files/Debian/setup.sh` 
* `https://exa.phys.s.u-tokyo.ac.jp/archive/MateriApps/apt/setup.sh`
