### ISSUE TITLE
MateriApps LIVE!を仮想マシンにインストールし配布

### ISSUE THREAD

**Issue by k-yoshimi** [cmsi/MateriAppsLive#65]

**Comment by wistaria** [comment]
VirtualBox用の配布イメージの自動生成に成功 #82 
次バージョンより
* 64bit (amd64) アーキテクチャ用 Live USB イメージ
* 32bit (i386) アーキテクチャ用 Live USB イメージ
* 64bit (amd64) アーキテクチャ用 VirutalBox イメージ
* 32bit (i386) アーキテクチャ用 VirtualBox イメージ
を配布予定
