### ISSUE TITLE
仮想マシンDocker

### ISSUE THREAD

**Issue by t-sakashita** [cmsi/MateriAppsLive#96]
AICS前田チームのPeter Bryzgalovさんが開発に貢献しているDockerについてのメモ。（AICS cafeより）

Dockerの特徴：
- Gitのようなコマンドで管理
- ソースファイル単位ではなく、バイナリ単位のパッケージ（コンテナと呼ばれる）で管理
- VirtualBoxなどと比較して、低オーバヘッド、低容量の仮想化を実現

参考：
- http://www.atmarkit.co.jp/ait/articles/1405/16/news032.html
- http://codezine.jp/article/detail/7894
- Docker hubで、パッケージのダウンロード、自分の作ったパッケージをpush/pullできるようだ。ドキュメンテーション、サンプルもある。（要Githubのアカウント、要登録）https://hub.docker.com/ 
- ホストOSがWindowで、ゲストOSをLinuxとすることもできるhttp://pocketstudio.jp/log3/2015/01/16/boot2docker_introduction/

以下に活用できるのでは？
- ハンズオン
- アプリの開発・テスト環境。その再現・共有
- MaterAppsLiveの配布（体験するだけなく、本番計算にも利用できる）

**Comment by wistaria** [comment]
packerを使って作成可

**Comment by wistaria** [comment]
Done in malive 4.0
