### ISSUE TITLE
Tapiocaのアップデート

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#97]

**Comment by yoshizk07** [comment]
TAPIOCAのアップデートの件ですが、
MateriAppsでは、ソースとWindowsとMacのバイナリを公開していますが、
Windowsのバイナリの方が間に合いそうにないのと、
まだちょっと修正したい所があるので、
MateriAppsでのアップデートは今月末にしたいと思っています。

しかし、金属学会の展示のMateriAppsLive!のデモでは現在のverisonより
アップデートしてものを使いたいので、
http://white.phys.s.u-tokyo.ac.jp/~yoshiz-k/tapioca.tgz
のTAPIOCAに、MateriAppsLive!をアップデートして頂けますか？
前のversionnの Makefile.inc でコンパイル可能だと思います。
どうぞよろしくお願いいたします。

**Comment by wistaria** [comment]
バージョン番号はどうしますか？ src/gloption.cc では 1.5.0 となっていますが、このバージョンを 1.5.0 として Debian package を作って公開して大丈夫ですか？

**Comment by yoshizk07** [comment]
説明不足ですみません。

＞このバージョンを 1.5.0 として Debian package を作って公開して大丈夫ですか？
それでお願いいたします。

**Comment by wistaria** [comment]
Done in d5507c16ea8e980562e0049713ff69da28287e02
