### ISSUE TITLE
MateriApps LIVE! 1.5のリリース

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#98]

**Comment by wistaria** [comment]
1.5b1を作成し、以下にアップロード済
https://sourceforge.net/projects/materiappslive/files/Release-1.5RC/

**Comment by yoshizk07** [comment]
藤堂先生アップロードどうもありがとうございました。
TAPIOCA1.5.0の動作を確認しましたが、今の所問題はありません。

**Comment by wistaria** [comment]
どなたか、Getting Startedの「アプリケーション毎の情報」の内容を全てのアプリについて動作確認おこなって、結果を報告してもらえませんか？

**Comment by yoshizk07** [comment]
昨日1.5b1をダウンロードしてTAPIOCAだけ試したのですが、
明日大学で、AkaiKKR、ALPS、feram、GAMESSを試してみます。
ALPSはチュートリアルをすべて試す必要がありますか？
これだけ試せば良いというのはありますか？

**Comment by yoshizk07** [comment]
Getting Started の OpenMXの所で、
/usr/share/openmx/work/Methane.dat
がありません。
どうぞよろしくお願い致します。

**Comment by yoshizk07** [comment]
すみません、OpenMX の
/usr/share/openmx/work/Methane.dat
はありました。（他にたくさんファイルがあって見落としました。）

Getting Started はすべて無事に終わりました。

**Comment by t-nissie** [comment]
MacBook Pro (Retina, 13-inch, Late 2012) で解像度変更のオプション vga=0x37e を追加してブートできました。feramだけですが、動作確認しました。https://github.com/cmsi/MateriAppsLive/wiki/MacBook に追記しました。

**Comment by wistaria** [comment]
確認ありがとうございます。問題なさそうなので、リリース作業に移ります。

**Comment by wistaria** [comment]
1.5b1 には XCrySDenが入っていませんでした。含めた上で 1.5 をリリースしました。現在 SourceForge https://sourceforge.net/projects/materiappslive/files/Release-1.5/ にアップロード中です。

**Comment by wistaria** [comment]
3/12の朝、MateriAppsのニュース更新、Forum告知、Twitterの告知を行います

**Comment by wistaria** [comment]
山崎さんに USB 作成依頼ずみ

**Comment by t-nissie** [comment]
正式リリースのisoイメージでのブートも確認しました。ありがとうございます！

README.mdの訂正（すべて小文字。version番号。）をお願いします。
誤: Feram (0.22.04-1)
正: feram (0.22.06-1)

MacBook Pro (Retina, 13-inch, Late 2012) では
Broadcomの無線LANチップが使えないことに
気がつきました。ひと工夫必要なようです。
参考: https://wiki.debian.org/MacBook/Wireless

**Comment by wistaria** [comment]
develop ブランチで修正しました。> @t-nissie

**Comment by wistaria** [comment]
MateriAppsのニュース更新、Forum告知、Twitter告知完了
